<a href="https://colab.research.google.com/github/a-nagar/cs4372/blob/main/Frequent_Pattern_Association_Rules_SOLN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%pip install mlxtend --upgrade

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

# Transactions Dataset
Let's look at a set of transactions stored in the form of a list with elements containing individual transactions.

In [3]:
dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [4]:
type(dataset)

list

## Converting to Transactions Dataframe
Before we can proceed, we need to convert the transaction list using TransactionEncoder object. Notice the format of the output dataframe.

In [5]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

# Apriori Algorithm
Let's run apriori algorithm and provide minimum support values.

In [6]:
from mlxtend.frequent_patterns import apriori

apriori(df, min_support=0.6, use_colnames=True)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

    support                     itemsets
0       0.8                       (Eggs)
1       1.0               (Kidney Beans)
2       0.6                       (Milk)
3       0.6                      (Onion)
4       0.6                     (Yogurt)
5       0.8         (Eggs, Kidney Beans)
6       0.6                (Eggs, Onion)
7       0.6         (Kidney Beans, Milk)
8       0.6        (Kidney Beans, Onion)
9       0.6       (Kidney Beans, Yogurt)
10      0.6  (Eggs, Kidney Beans, Onion)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

# Frequent Itemsets
Let's create frequent items sets with minimum support.

In [7]:
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

    support                     itemsets  length
0       0.8                       (Eggs)       1
1       1.0               (Kidney Beans)       1
2       0.6                       (Milk)       1
3       0.6                      (Onion)       1
4       0.6                     (Yogurt)       1
5       0.8         (Eggs, Kidney Beans)       2
6       0.6                (Eggs, Onion)       2
7       0.6         (Kidney Beans, Milk)       2
8       0.6        (Kidney Beans, Onion)       2
9       0.6       (Kidney Beans, Yogurt)       2
10      0.6  (Eggs, Kidney Beans, Onion)       3

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [8]:
frequent_itemsets[ (frequent_itemsets['length'] >= 2) &
                   (frequent_itemsets['support'] >= 0.6) ]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

    support                     itemsets  length
5       0.8         (Eggs, Kidney Beans)       2
6       0.6                (Eggs, Onion)       2
7       0.6         (Kidney Beans, Milk)       2
8       0.6        (Kidney Beans, Onion)       2
9       0.6       (Kidney Beans, Yogurt)       2
10      0.6  (Eggs, Kidney Beans, Onion)       3

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

# Association Rules
Next, let's try to find association rules with significan confidence values from the transaction dataset.

In [9]:
import warnings
warnings.filterwarnings('ignore')

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [10]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7, num_itemsets=df.shape[0])

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.00,1.00,1.0,0.00,inf,0.0,0.80,0.000,0.900
1,(Kidney Beans),(Eggs),1.0,0.8,0.8,0.80,1.00,1.0,0.00,1.0,0.0,0.80,0.000,0.900
2,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
3,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
4,(Milk),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
5,(Onion),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
6,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
7,"(Eggs, Kidney Beans)",(Onion),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
8,"(Eggs, Onion)",(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
9,"(Kidney Beans, Onion)",(Eggs),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
10,(Eggs),"(Kidney Beans, Onion)",0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
11,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875

Let's try to create a column with the length of items in each antecedent.

In [11]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2, num_itemsets=df.shape[0])
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,antecedent_len
0,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875,1
1,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875,1
2,"(Eggs, Kidney Beans)",(Onion),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875,2
3,"(Kidney Beans, Onion)",(Eggs),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875,2
4,(Eggs),"(Kidney Beans, Onion)",0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875,1
5,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875,1

The above information can be used for filtering rules with sufficient number of items in antecedent or consequent.

In [12]:
rules[ (rules['antecedent_len'] >= 2) &
       (rules['confidence'] > 0.75) &
       (rules['lift'] > 1.2) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,antecedent_len
3,"(Kidney Beans, Onion)",(Eggs),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875,2

# FP Growth Algorithm

FP Growth is a faster alternative to Apriori algorithm that doesn't involve explicit candidate generation.

As per documentation, "*In particular, and what makes it different from the Apriori frequent pattern mining algorithm, FP-Growth is an frequent pattern mining algorithm that does not require candidate generation. Internally, it uses a so-called FP-tree (frequent pattern tree) datastrucure without generating the candidate sets explicitely, which makes is particularly attractive for large datasets.*"

In [13]:
from mlxtend.frequent_patterns import fpgrowth

fpgrowth(df, min_support=0.6, use_colnames=True)

    support                     itemsets
0       1.0               (Kidney Beans)
1       0.8                       (Eggs)
2       0.6                     (Yogurt)
3       0.6                       (Milk)
4       0.6                      (Onion)
5       0.8         (Eggs, Kidney Beans)
6       0.6       (Kidney Beans, Yogurt)
7       0.6         (Kidney Beans, Milk)
8       0.6                (Eggs, Onion)
9       0.6        (Kidney Beans, Onion)
10      0.6  (Eggs, Kidney Beans, Onion)

If you just want the maximal patterns, you can use *fpmax* algorithm.

As per documentation, "*FP-Max is a variant of FP-Growth, which focuses on obtaining maximal itemsets. An itemset X is said to maximal if X is frequent and there exists no frequent super-pattern containing X. In other words, a frequent pattern X cannot be sub-pattern of larger frequent pattern to qualify for the definition maximal itemset.*"

In [14]:
from mlxtend.frequent_patterns import fpmax
fpmax(df, min_support=0.6, use_colnames=True)

   support                     itemsets
0      0.6  (Eggs, Kidney Beans, Onion)
1      0.6         (Kidney Beans, Milk)
2      0.6       (Kidney Beans, Yogurt)

# Working With A Real Dataset
Let's work with a dataset from UCI repository: https://archive.ics.uci.edu/ml/datasets/online+retail

We will download the file and read it into a Pandas dataframe.

In [15]:
import pandas as pd
df = pd.read_excel('http://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

Let's get rid of any null or missing invoice values and convert them to string format.

In [16]:
df.dropna(axis=0, subset=['InvoiceNo'], inplace=True)
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df = df[~df['InvoiceNo'].str.contains('C')]

In [17]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

**This is an important step**.

You need to convert data into the form that the package expects i.e. transaction id along rows and one column for each item.

In [18]:
basket = (df[df['Country'] =="France"]
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))

Don't be surprised if you see lots of 0's.

In [19]:
basket.iloc[:100, :]

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536974,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548496,0.0,0.0,0.0,0.0,72.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
548553,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
548606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
548725,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
548737,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

I would like to convert data into only 0 or 1.

In [20]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

basket_sets = basket.applymap(encode_units)

In [21]:
basket_sets.iloc[:100, :]

Description,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TRELLIS COAT RACK,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548496,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
548553,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
548606,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
548725,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
548737,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
frequent_itemsets = apriori(basket_sets, min_support=0.07, use_colnames=True)

In [23]:
frequent_itemsets

     support                                           itemsets
0   0.071429                      (4 TRADITIONAL SPINNING TOPS)
1   0.096939                       (ALARM CLOCK BAKELIKE GREEN)
2   0.102041                        (ALARM CLOCK BAKELIKE PINK)
3   0.094388                        (ALARM CLOCK BAKELIKE RED )
4   0.081633                    (BAKING SET 9 PIECE RETROSPOT )
..       ...                                                ...
85  0.084184  (SET/20 RED RETROSPOT PAPER NAPKINS , POSTAGE,...
86  0.084184  (SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RE...
87  0.102041  (SET/6 RED SPOTTY PAPER PLATES, POSTAGE, SET/6...
88  0.099490  (SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RE...
89  0.081633  (SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RE...

[90 rows x 2 columns]

In [24]:
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets.head()

    support                         itemsets  length
0  0.071429    (4 TRADITIONAL SPINNING TOPS)       1
1  0.096939     (ALARM CLOCK BAKELIKE GREEN)       1
2  0.102041      (ALARM CLOCK BAKELIKE PINK)       1
3  0.094388      (ALARM CLOCK BAKELIKE RED )       1
4  0.081633  (BAKING SET 9 PIECE RETROSPOT )       1

In [25]:
pd.set_option('max_colwidth', 600)
frequent_itemsets[ (frequent_itemsets['length'] >= 2) &
                   (frequent_itemsets['support'] >= 0.07) ].sort_values(by="length", ascending=False)

,support,itemsets,length
89,0.081633,"(SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RED SPOTTY PAPER PLATES, POSTAGE, SET/6 RED SPOTTY PAPER CUPS)",4
83,0.084184,"(PLASTERS IN TIN WOODLAND ANIMALS, PLASTERS IN TIN CIRCUS PARADE , POSTAGE)",3
81,0.071429,"(ALARM CLOCK BAKELIKE GREEN, ALARM CLOCK BAKELIKE RED , POSTAGE)",3
86,0.084184,"(SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RED SPOTTY PAPER PLATES, POSTAGE)",3
87,0.102041,"(SET/6 RED SPOTTY PAPER PLATES, POSTAGE, SET/6 RED SPOTTY PAPER CUPS)",3
82,0.073980,"(PLASTERS IN TIN CIRCUS PARADE , POSTAGE, PLASTERS IN TIN SPACEBOY)",3
84,0.084184,"(PLASTERS IN TIN WOODLAND ANIMALS, POSTAGE, PLASTERS IN TIN SPACEBOY)",3
85,0.084184,"(SET/20 RED RETROSPOT PAPER NAPKINS , POSTAGE, SET/6 RED SPOTTY PAPER CUPS)",3
88,0.099490,"(SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOTTY PAPER CUPS)",3
42,0.079082,"(ALARM CLOCK BAKELIKE GREEN, ALARM CLOCK BAKELIKE RED )",2
43,0.084184,"(ALARM CLOCK BAKELIKE GREEN, POSTAGE)",2
44,0.073980,"(ALARM CLOCK BAKELIKE RED , ALARM CLOCK BAKELIKE PINK)",2
45,0.089286,"(ALARM CLOCK BAKELIKE PINK, POSTAGE)",2
46,0.086735,"(ALARM CLOCK BAKELIKE RED , POSTAGE)",2
47,0.073980,"(DOLLY GIRL LUNCH BOX, POSTAGE)",2
48,0.071429,"(SPACEBOY LUNCH BOX , DOLLY GIRL LUNCH BOX)",2
41,0.073980,"(ALARM CLOCK BAKELIKE GREEN, ALARM CLOCK BAKELIKE PINK)",2
57,0.084184,"(PACK OF 72 RETROSPOT CAKE CASES, POSTAGE)",2
56,0.081633,"(POSTAGE, MINI PAINT SET VINTAGE )",2
55,0.114796,"(LUNCH BOX WITH CUTLERY RETROSPOT , POSTAGE)",2
54,0.102041,"(LUNCH BAG WOODLAND, POSTAGE)",2
53,0.091837,"(LUNCH BAG SPACEBOY DESIGN , POSTAGE)",2
52,0.122449,"(POSTAGE, LUNCH BAG RED RETROSPOT)",2
51,0.104592,"(POSTAGE, LUNCH BAG APPLE DESIGN)",2
50,0.076531,"(POSTAGE, JUMBO BAG WOODLAND ANIMALS)",2
49,0.081633,"(POSTAGE, JUMBO BAG RED RETROSPOT)",2
58,0.071429,"(PAPER BUNTING RETROSPOT, POSTAGE)",2
60,0.102041,"(PLASTERS IN TIN WOODLAND ANIMALS, PLASTERS IN TIN CIRCUS PARADE )",2
59,0.089286,"(PLASTERS IN TIN CIRCUS PARADE , PLASTERS IN TIN SPACEBOY)",2
62,0.104592,"(PLASTERS IN TIN WOODLAND ANIMALS, PLASTERS IN TIN SPACEBOY)",2
63,0.114796,"(POSTAGE, PLASTERS IN TIN SPACEBOY)",2
64,0.137755,"(PLASTERS IN TIN WOODLAND ANIMALS, POSTAGE)",2
61,0.147959,"(PLASTERS IN TIN CIRCUS PARADE , POSTAGE)",2
73,0.117347,"(POSTAGE, SET/6 RED SPOTTY PAPER CUPS)",2
72,0.109694,"(SET/20 RED RETROSPOT PAPER NAPKINS , POSTAGE)",2
71,0.147959,"(ROUND SNACK BOXES SET OF4 WOODLAND , POSTAGE)",2
70,0.094388,"(POSTAGE, ROUND SNACK BOXES SET OF 4 FRUITS )",2
69,0.104592,"(REGENCY CAKESTAND 3 TIER, POSTAGE)",2
68,0.158163,"(RED TOADSTOOL LED NIGHT LIGHT, POSTAGE)",2
67,0.114796,"(POSTAGE, RED RETROSPOT MINI CASES)",2
66,0.081633,"(RED RETROSPOT CHARLOTTE BAG, POSTAGE)",2
65,0.165816,"(RABBIT NIGHT LIGHT, POSTAGE)",2
80,0.122449,"(SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOTTY PAPER CUPS)",2
78,0.102041,"(SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RED SPOTTY PAPER CUPS)",2
79,0.102041,"(SET/20 RED RETROSPOT PAPER NAPKINS , SET/6 RED SPOTTY PAPER PLATES)",2
75,0.096939,"(SPACEBOY LUNCH BOX , POSTAGE)",2
76,0.114796,"(STRAWBERRY LUNCH BOX WITH CUTLERY, POSTAGE)",2
74,0.107143,"(SET/6 RED SPOTTY PAPER PLATES, POSTAGE)",2
77,0.089286,"(TEA PARTY BIRTHDAY CARD, POSTAGE)",2

In [26]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1, num_itemsets=basket.shape[0])
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE PINK),0.096939,0.102041,0.073980,0.763158,7.478947,1.0,0.064088,3.791383,0.959283,0.591837,0.736244,0.744079
1,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE GREEN),0.102041,0.096939,0.073980,0.725000,7.478947,1.0,0.064088,3.283859,0.964734,0.591837,0.695480,0.744079
2,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.096939,0.094388,0.079082,0.815789,8.642959,1.0,0.069932,4.916181,0.979224,0.704545,0.796590,0.826814
3,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.094388,0.096939,0.079082,0.837838,8.642959,1.0,0.069932,5.568878,0.976465,0.704545,0.820431,0.826814
4,(ALARM CLOCK BAKELIKE GREEN),(POSTAGE),0.096939,0.765306,0.084184,0.868421,1.134737,1.0,0.009996,1.783673,0.131484,0.108197,0.439359,0.489211

# Lab Assignment
You will use the MovieLens 100K dataset available from
https://grouplens.org/datasets/movielens/

We will use the version for education and research. I have already uploaded the relevant files on the server and below is the command to read the files.

In [27]:
movies = pd.read_csv("https://an-ml.s3.us-west-1.amazonaws.com/ml-latest-small/movies.csv")

In [28]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [29]:
ratings = pd.read_csv("https://an-ml.s3.us-west-1.amazonaws.com/ml-latest-small/ratings.csv")

In [30]:
ratings_count = ratings.groupby('movieId')['rating'].count().reset_index(name='countOfRatings').sort_values(by='countOfRatings', ascending=False)
ratings_count

      movieId  countOfRatings
314       356             329
277       318             317
257       296             307
510       593             279
1938     2571             278
...       ...             ...
9707   190207               1
9706   190183               1
9705   189713               1
9704   189547               1
9703   189381               1

[9724 rows x 2 columns]

In [37]:
frequent_movies_ratings = pd.merge(ratings_count[ratings_count['countOfRatings'] > 200], ratings, on="movieId")

Let's join the above two tables on the common key movieId.

In [38]:
df = pd.merge(frequent_movies_ratings, movies, on="movieId")[['userId', 'title', 'rating']]

In [33]:
df.head()

   userId             title  rating
0       1  Toy Story (1995)     4.0
1       5  Toy Story (1995)     4.0
2       7  Toy Story (1995)     4.5
3      15  Toy Story (1995)     2.5
4      17  Toy Story (1995)     4.5

The columns of interest to us are title and userId. Now, repeat the steps that we did earlier and find significant frequent patterns and association rules. You are free to set the selection paramters.

*Optional* - Do the results make sense? Use your knowledge of movies 😀

In [39]:
basket = (df
          .groupby(['userId', 'title'])['rating']
          .count().unstack().reset_index().fillna(0)
          .set_index('userId'))

In [35]:
basket.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
from mlxtend.frequent_patterns import apriori
frequent_itemsets = apriori(basket, min_support=0.07, use_colnames=True)

In [41]:
frequent_itemsets

,support,itemsets
0,0.364286,(American Beauty (1999))
1,0.358929,(Apollo 13 (1995))
2,0.423214,(Braveheart (1995))
3,0.389286,(Fight Club (1999))
4,0.587500,(Forrest Gump (1994))
...,...,...
45979,0.071429,"(Terminator 2: Judgment Day (1991), Silence of the Lambs, The (1991), Star Wars: Episode V - The Empire Strikes Back (1980), Pulp Fiction (1994), Fight Club (1999), Shawshank Redemption, The (1994), Matrix, The (1999), Independence Day (a.k.a. ID4) (1996), Usual Suspects, The (1995), Star Wars: Episode IV - A New Hope (1977), Jurassic Park (1993))"
45980,0.071429,"(Terminator 2: Judgment Day (1991), Silence of the Lambs, The (1991), Star Wars: Episode IV - A New Hope (1977), Star Wars: Episode V - The Empire Strikes Back (1980), Pulp Fiction (1994), Shawshank Redemption, The (1994), Matrix, The (1999), Independence Day (a.k.a. ID4) (1996), Seven (a.k.a. Se7en) (1995), Forrest Gump (1994), Jurassic Park (1993))"
45981,0.071429,"(Terminator 2: Judgment Day (1991), Star Wars: Episode IV - A New Hope (1977), Star Wars: Episode V - The Empire Strikes Back (1980), Pulp Fiction (1994), Fight Club (1999), Shawshank Redemption, The (1994), Matrix, The (1999), Braveheart (1995), Independence Day (a.k.a. ID4) (1996), Seven (a.k.a. Se7en) (1995), Forrest Gump (1994), Jurassic Park (1993))"
45982,0.073214,"(Terminator 2: Judgment Day (1991), Silence of the Lambs, The (1991), Star Wars: Episode IV - A New Hope (1977), Star Wars: Episode V - The Empire Strikes Back (1980), Pulp Fiction (1994), Fight Club (1999), Shawshank Redemption, The (1994), Matrix, The (1999), Braveheart (1995), Independence Day (a.k.a. ID4) (1996), Forrest Gump (1994), Jurassic Park (1993))"
45983,0.071429,"(Terminator 2: Judgment Day (1991), Star Wars: Episode IV - A New Hope (1977), Star Wars: Episode V - The Empire Strikes Back (1980), Pulp Fiction (1994), Fight Club (1999), Shawshank Redemption, The (1994), Matrix, The (1999), Braveheart (1995), Independence Day (a.k.a. ID4) (1996), Forrest Gump (1994), Jurassic Park (1993), Toy Story (1995))"

In [42]:
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets.head()

    support                  itemsets  length
0  0.364286  (American Beauty (1999))       1
1  0.358929        (Apollo 13 (1995))       1
2  0.423214       (Braveheart (1995))       1
3  0.389286       (Fight Club (1999))       1
4  0.587500     (Forrest Gump (1994))       1

In [43]:
pd.set_option('max_colwidth', 600)
frequent_itemsets[ (frequent_itemsets['length'] >= 3) &
                   (frequent_itemsets['support'] >= 0.07) ].sort_values(by="support", ascending=False)

,support,itemsets,length
658,0.319643,"(Shawshank Redemption, The (1994), Forrest Gump (1994), Pulp Fiction (1994))",3
882,0.294643,"(Shawshank Redemption, The (1994), Silence of the Lambs, The (1991), Pulp Fiction (1994))",3
659,0.292857,"(Forrest Gump (1994), Silence of the Lambs, The (1991), Pulp Fiction (1994))",3
857,0.289286,"(Star Wars: Episode IV - A New Hope (1977), Matrix, The (1999), Star Wars: Episode V - The Empire Strikes Back (1980))",3
636,0.282143,"(Forrest Gump (1994), Jurassic Park (1993), Pulp Fiction (1994))",3
...,...,...,...
45881,0.071429,"(Terminator 2: Judgment Day (1991), Star Wars: Episode IV - A New Hope (1977), Star Wars: Episode V - The Empire Strikes Back (1980), Shawshank Redemption, The (1994), Matrix, The (1999), Independence Day (a.k.a. ID4) (1996), Usual Suspects, The (1995), Seven (a.k.a. Se7en) (1995), Forrest Gump (1994), Jurassic Park (1993))",10
45880,0.071429,"(Terminator 2: Judgment Day (1991), Silence of the Lambs, The (1991), Star Wars: Episode IV - A New Hope (1977), Star Wars: Episode V - The Empire Strikes Back (1980), Shawshank Redemption, The (1994), Matrix, The (1999), Independence Day (a.k.a. ID4) (1996), Seven (a.k.a. Se7en) (1995), Forrest Gump (1994), Jurassic Park (1993))",10
45879,0.071429,"(Terminator 2: Judgment Day (1991), Star Wars: Episode IV - A New Hope (1977), Star Wars: Episode V - The Empire Strikes Back (1980), Pulp Fiction (1994), Matrix, The (1999), Independence Day (a.k.a. ID4) (1996), Usual Suspects, The (1995), Forrest Gump (1994), Jurassic Park (1993), Toy Story (1995))",10
45874,0.071429,"(Terminator 2: Judgment Day (1991), Silence of the Lambs, The (1991), Star Wars: Episode IV - A New Hope (1977), Pulp Fiction (1994), Shawshank Redemption, The (1994), Matrix, The (1999), Independence Day (a.k.a. ID4) (1996), Forrest Gump (1994), Jurassic Park (1993), Toy Story (1995))",10
45873,0.071429,"(Silence of the Lambs, The (1991), Star Wars: Episode IV - A New Hope (1977), Star Wars: Episode V - The Empire Strikes Back (1980), Pulp Fiction (1994), Shawshank Redemption, The (1994), Matrix, The (1999), Independence Day (a.k.a. ID4) (1996), Usual Suspects, The (1995), Forrest Gump (1994), Jurassic Park (1993))",10

In [44]:
from mlxtend.frequent_patterns import association_rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1).sort_values(by="confidence", ascending=False)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
3471695,"(Fight Club (1999), Braveheart (1995), Jurassic Park (1993), Seven (a.k.a. Se7en) (1995), Star Wars: Episode IV - A New Hope (1977), Terminator 2: Judgment Day (1991))","(Matrix, The (1999), Pulp Fiction (1994))",0.078571,0.317857,0.078571,1.0,3.146067,1.0,0.053597,inf,0.740310,0.247191,1.0,0.623596
3429256,"(Silence of the Lambs, The (1991), Fight Club (1999), Shawshank Redemption, The (1994), Braveheart (1995), Independence Day (a.k.a. ID4) (1996), Star Wars: Episode IV - A New Hope (1977), Jurassic Park (1993))",(Pulp Fiction (1994)),0.076786,0.548214,0.076786,1.0,1.824104,1.0,0.034691,inf,0.489362,0.140065,1.0,0.570033
4171952,"(Matrix, The (1999), Independence Day (a.k.a. ID4) (1996), Forrest Gump (1994), Usual Suspects, The (1995), Seven (a.k.a. Se7en) (1995), Star Wars: Episode IV - A New Hope (1977), Jurassic Park (1993))",(Star Wars: Episode V - The Empire Strikes Back (1980)),0.085714,0.376786,0.085714,1.0,2.654028,1.0,0.053418,inf,0.681641,0.227488,1.0,0.613744
4492120,"(Fight Club (1999), Shawshank Redemption, The (1994), Matrix, The (1999), Braveheart (1995), Independence Day (a.k.a. ID4) (1996), Star Wars: Episode IV - A New Hope (1977), Jurassic Park (1993), American Beauty (1999))",(Star Wars: Episode V - The Empire Strikes Back (1980)),0.073214,0.376786,0.073214,1.0,2.654028,1.0,0.045628,inf,0.672447,0.194313,1.0,0.597156
5662566,"(Pulp Fiction (1994), Fight Club (1999), Shawshank Redemption, The (1994), Independence Day (a.k.a. ID4) (1996), Forrest Gump (1994), Seven (a.k.a. Se7en) (1995), Star Wars: Episode IV - A New Hope (1977), Terminator 2: Judgment Day (1991))","(Matrix, The (1999))",0.080357,0.496429,0.080357,1.0,2.014388,1.0,0.040466,inf,0.547573,0.161871,1.0,0.580935